### ISSUE TITLE
Stimulus does not show up when running demoexperiment

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/website#15]
I have uploaded a demo experiment and the necessary fonts to the easyeyes.app platform, but I am having trouble displaying the font after completing the consent form and calibration process. 
<img width="757" alt="easyeyes_demo_readytorun" src="https://user-images.githubusercontent.com/117389237/222214757-08193cf3-d4de-4f13-a5fa-b7dea9129ee4.PNG">
389237/222214731-2cbecc04-bd95-4255-a787-44785c420ac7.PNG">

The screen appears to be stuck on the "Initializing the Experiment" stage after calibration.
<img width="651" alt="Initializingscreen" src="https://user-images.githubusercontent.com/117389237/222214891-dade3fce-2a01-4356-9b76-55a092b84d8c.PNG">

**Comment by peilingjiang** [comment]
Hi @sravyam28 I tried the study URL in the screenshot. The problem is straightforward - you did not have enough Credit in your Pavlovia account. Sorry that we are not making this error obvious. Please go to https://pavlovia.org/docs/credit-license/overview to learn more about Credits and purchase on their site for your Pavlovia account.

EasyEyes compiles the experiment table and sends it to Pavlovia.

**Comment by sravyam28** [comment]
That makes sense. Thanks @peilingjiang
